// <auto-generated />
namespace RockRecord.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class removeTestData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeTestData));
        
        string IMigrationMetadata.Id
        {
            get { return "201307070530092_removeTestData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
