// <auto-generated />
namespace RockRecord.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class newreview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newreview));
        
        string IMigrationMetadata.Id
        {
            get { return "201304090836417_newreview"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
